# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    basic_premium: 500

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones


    # age use case
    app.age_rating_repo:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - App\Entity\AgeRating

    app.age_use_case:
        class: App\Service\AgeUseCase
        arguments:
            - '@app.age_rating_repo'
            - '@request_stack'

    App\Service\AgeUseCase: '@app.age_use_case'

    # postcode use case
    app.postcode_rating_repo:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - App\Entity\PostcodeRating

    app.postcode_use_case:
        class: App\Service\PostcodeUseCase
        arguments:
            - '@app.postcode_rating_repo'
            - '@request_stack'

    App\Service\PostcodeUseCase: '@app.postcode_use_case'


    # reg number use case
    app.abi_code_rating_repo:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - App\Entity\AbiCodeRating

    guzzle_client:
        class: GuzzleHttp\Client

    app.abi_lookup_service:
        class: App\Service\AbiCodeLookup
        arguments:
            - "@guzzle_client"
            - '@request_stack'
    App\Service\AbiCodeLookup: '@app.abi_lookup_service'

    app.reg_number_use_case:
        class: App\Service\RegNumberUseCase
        arguments:
            - '@app.abi_lookup_service'
            - '@app.abi_code_rating_repo'

    App\Service\RegNumberUseCase: '@app.reg_number_use_case'

    # quote calculator
    # any new use case can be added to quote calculator
    app.quote_calculator:
        class: App\Service\QuoteCalculator
        arguments:
            $basicPremium:  '%basic_premium%'
            $useCases:      ['@app.age_use_case']
#'@app.postcode_use_case','@app.reg_number_use_case',
    App\Service\QuoteCalculator: '@app.quote_calculator'